version: '3.8'

services:
  app:
    build: ./php
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: secret
      DB_NAME: app_db
      DB_PORT: 5445
    networks:
      - app-network

  db:
    image: postgres:15  # Облегченная версия
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network
    ports:
      - "5445:5445"

  phpmyadmin:
    image: adminer  # Альтернатива phpMyAdmin для PostgreSQL
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
