# Dockerfile
FROM php:8.1-apache

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Включение mod_rewrite
RUN a2enmod rewrite

# Копируем исходный код
COPY . /var/www/html/

# Устанавливаем права
RUN chown -R www-data:www-data /var/www/html